### PR TITLE
Allow user to avoid/postpone waiting for connect

### PR DESCRIPTION
**Pull request by jbemmel**
In my application I have a need to start the connection early on, and postpone waiting until I need it

### CODE REVIEW

**Comment by akarneliuk** [comment]
Hey @jbemmel ,

Thanks for contribution as always. I'm thinking on 
```
        if self.__gnmi_timeout is None or self.__gnmi_timeout > 0:
           self.wait_for_connect()
```
Basicaly, in any case you are invokining `wait_for_connect()` method. How would it help to achieve your goal?

Best,
Anton

**Comment by jbemmel** [comment]
It allows me to set timeout=0 and skip the wait

I am using Ryu which is based on eventlet, I suspect it’s incompatible with the blocking wait. I just need a way to postpone/skip it

**Comment by akarneliuk** [comment]
It makes sense then.

Thanks, merged.

**Comment by jbemmel** [comment]
Actually, we need to make the timeout a parameter of wait_for_connect - I can send an update

**Pull request merged**
